version: '3.8'

services:
  validator:
    build: .
    env_file: .env
    restart: always
    container_name: smarteros-gatekeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/smarteros/docs:/opt/smarteros/docs
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
